export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';
export const GET_REPOS = 'GET_REPOS';
export const NO_REPOS = 'NO_REPOS';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';
export const GET_SEARCH = 'GET_SEARCH';
export const POST_ERROR = 'POST_ERROR';
export const GET_POSTS = 'GET_POSTS';
export const UPDATE_LIKES = 'UPDATE_LIKES';
export const DELETE_POST = 'DELETE_POST';
export const ADD_POST = 'ADD_POST';
export const GET_POST = 'GET_POST';
export const ADD_COMMENT = ' ADD_COMMENT';

export const ADD_INGREDIENTS = 'ADD_INGREDIENTS';
export const REMOVE_COMMENT = 'REMOVE_COMMENT';
export const GET_INGREDIENTS = 'GET_INGREDIENTS';
export const GET_INGREDIENTSS = 'GET_INGREDIENTSS';
export const EDIT_INGREDIENTS = 'EDIT_INGREDIENTS';
export const DELETE_INGREDIENTS = 'DELETE_INGREDIENTS';
export const ERROR_INGREDIENTS = 'ERROR_INGREDIENTS';
export const CLOSE_INGREDIENTS = 'CLOSE_INGREDIENTS';

export const ADD_TABLES = 'ADD_TABLES';
export const GET_TABLES = 'GET_TABLES';
export const GET_TABLESS = 'GET_TABLESS';
export const EDIT_TABLES = 'EDIT_TABLES';
export const DELETE_TABLES = 'DELETE_TABLES';
export const ERROR_TABLES = 'ERROR_TABLES';

export const ADD_PRODUITS = 'ADD_PRODUITS';
export const GET_PRODUITS = 'GET_PRODUITS';
export const GET_PRODUITSS = 'GET_PRODUITSS';
export const EDIT_PRODUITS = 'EDIT_PRODUITS';
export const DELETE_PRODUITS = 'DELETE_PRODUITS';
export const ERROR_PRODUITS = 'ERROR_PRODUITS';

export const ADD_RESERVATIONS = 'ADD_RESERVATIONS';
export const GET_RESERVATIONS = 'GET_RESERVATIONS';
export const GET_RESERVATIONSS = 'GET_RESERVATIONSS';
export const EDIT_RESERVATIONS = 'EDIT_RESERVATIONS';
export const DELETE_RESERVATIONS = 'DELETE_RESERVATIONS';
export const ERROR_RESERVATIONSS = 'ERROR_RESERVATIONSS';

